### ISSUE TITLE
Teste do cucumber de remover tarefa está falhando

### ISSUE THREAD

**Issue by ksar79** [andregomes53/Grape#21]
Teste com mais de uma tarefa falhou.
Ambiguous match, found 3 elements matching visible link or button "Remover Tarefa" (Capybara::Ambiguous)

**Comment by leostb** [comment]
Eu sei resolver, acontece que quando fizemos o teste não pensei que ele teria mais de uma tarefa no banco. Ainda não sei como funciona a execução dos testes.

**Comment by andregomes53** [comment]
Já foi arrumado.
