### ISSUE TITLE
O sistema de senhas não tem nenhuma segurança

### ISSUE THREAD

**Issue by min4builder** [andregomes53/Grape#27]
As senhas são armazenadas em texto plano. Isso em si já é problemático.

Os critérios de senha são:
- Só letras e números são permitidos (ruim, diminui o conjunto de caracteres)
- Pelo menos três dentre: letra maiúscula, letra minúscula, número e mais de 10 caracteres (ok)
- Entre 8 e 15 caracteres (**péssimo**, restringe a senhas curtas)

O [recomendado](https://blog.codinghorror.com/your-password-is-too-damn-short/) é que o usuário tenha uma senha longa, no mínimo 12 caracteres, e a senha seja armazenada como um hash seguro (e lento de calcular).
O uso de letras maiúsculas, números e caracteres especiais (especialmente Unicode) ajuda, mas o que mais influencia na dificuldade de descobrir uma senha é o tamanho.

O método passwordStrength poderia ser tão simples quanto:
```ruby
def passwordStrength
    user_params[:password].length > 12
end
```

**Comment by andregomes53** [comment]
Oi Lucas,

Então, na verdade as nossas a senha é criptografada no Model do Usuário, por isso instalamos o BCrypt, como você deve ter visto no Gemfile. Ou seja, não estamos salvando texto plano (inclusive estavamos tendo um erro em um dos nossos testes porque estavamos tentando comparar a senha que o usuário envia do front com a senha armazenada no banco de dados).

O método passwordStrength foi criado para para adicionar restrições que nós impomos usando as informações recebidas da view, além das validações já presentes no Modelo.

Concordo que senha muito longa seja um caso de erro ruim da maneira que está implementado. Porém o caso senha muito longa ainda é válido, visto que o BCrypt aceita senhas com um tamanho máximo de 50-72 bytes. Em outras palavras esta validação já deve ser feita pelo nosso modelo, só precisa alterar o caso de teste.

Eu recomendaria criar uma história de usuário para arrumar isso, algo como "Como usuário, quero poder cadastrar uma senha com mais de 15 caracteres, de modo que...". Você mesmo pode criar e implementar inclusive :)

De resto acho que o método é válido, se quiser podemos alterar para poder colocar caracteres especiais, mas acho que não é uma prioridade.

Valeu pelo toque Lucas!

**Comment by min4builder** [comment]
> Ou seja, não estamos salvando texto plano (inclusive estavamos tendo um erro em um dos nossos testes porque estavamos tentando comparar a senha que o usuário envia do front com a senha armazenada no banco de dados).

Ah, entendi. Eu vi que a validação de senha comparava diretamente e assumi que a senha estivesse em texto plano (de qualquer forma, por que tem código que não funciona no repositório? normalmente só se faz commit com os testes passando).

> visto que o BCrypt aceita senhas com um tamanho máximo de 50-72 bytes

Então o limite deveria ser 72 bytes, não 15.

> se quiser podemos alterar para poder colocar caracteres especiais

O meu argumento era precisamente que isso não é necessário. O tamanho é o que mais influencia na segurança, por isso o tamanho mínimo mas não máximo (tanto que a senha ideal é uma frase completa).

> Você mesmo pode criar e implementar inclusive :)

Essa era a minha intenção, só não queria chegar mexendo no código dos outros sem conversar antes.

**Comment by min4builder** [comment]
Aliás, só para registro, a forma correta de autenticar uma senha no ActiveModel é:
```ruby
user.authenticate(password)
```
